#:schema node_modules/wrangler/config-schema.json
name = "ip-access-rule-generator"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[vars]
apiKey='your global API KEY'
apiEmail='your Email'
ZONEID='target Zone'
